### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by JakubRuzicka** [Zcgleaddev/ZCGZlancer#1]
Hi,
You put  token source code to gitignore  fix it please

**Comment by Zcgleaddev** [comment]
This issue is fixed. The code in gitignore is outdated and now superseded by the new code in the root folder.

**Comment by JakubRuzicka** [comment]
Are u fucking kiding me?

**Comment by JakubRuzicka** [comment]
awsome dont forgive to remove it from gitignore
